#!/bin/bash
set -e
cd ${0%/*} || exit 1
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# creating polyMesh,logs and running blockMesh

mkdir -p postProcessing/probes
mkdir -p logs
mkdir -p constant/polyMesh
cp -f save/blockMeshDict constant/polyMesh/


echo "Running blockMesh..."
blockMesh > logs/log.blockMesh 2>&1


# loops for refinement of mesh and wake from object
for i in 1
do
echo "Refining Wide Region (Iteration $i)..."
cp save/refineMeshDict.wide system/refineMeshDict
rm -f log.cellSet log.refineMesh
cp save/cellSetDict.wide system/cellSetDict
cellSet >> logs/log.cellSetWide 2>&1
refineMesh -dict -overwrite >> logs/log.refineMeshWide 2>&1
done


for i in 1 2
do
echo "Refining Medium Region (Iteration $i)..."
cp save/refineMeshDict.medium system/refineMeshDict
rm -f log.cellSet log.refineMesh
cp save/cellSetDict.medium system/cellSetDict
cellSet >> logs/log.cellSetMedium 2>&1
refineMesh -dict -overwrite >> logs/log.refineMeshMedium 2>&1
done

for i in 1 2
do
echo "Refining Tight Region (Iteration $i)..."
rm -f log.cellSet log.refineMesh
cp save/refineMeshDict.tight system/refineMeshDict
cp save/cellSetDict.tight system/cellSetDict
cellSet >> logs/log.cellSetTight 2>&1
refineMesh -dict -overwrite >> logs/log.refineMeshTight 2>&1
done



echo "Creating Vegetation Zone..."
rm -f log.cellSet log.refineHexMesh
cp save/cellSetDict.cyl system/cellSetDict
cellSet >> logs/log.cellSetVeg 2>&1

echo "Converting sets to zones..."
setsToZones -noFlipMap >> logs/log.setsToZones 2>&1

# echo "Setting values within plant..."
# setFields >> logs/log.setFields 2>&1
